# Generated by Django 4.1.1 on 2022-11-09 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('tital', models.CharField(max_length=40)),
                ('des', models.TextField()),
                ('id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
