# Generated by Django 4.1.1 on 2022-11-09 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0002_post_uid_remove_post_id_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.ManyToManyField(default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
