# Generated by Django 4.1.1 on 2022-11-09 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0003_alter_post_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uid',
        ),
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
